-- Demo Corp schemas — generated by tests.fixtures.demo_corp.generate
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS clinical CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS audit_internal CASCADE;

CREATE SCHEMA public;
CREATE SCHEMA clinical;
CREATE SCHEMA auth;
CREATE SCHEMA audit_internal;

CREATE EXTENSION IF NOT EXISTS ltree;
