"""DDL sections for MedicalHelpDesk Corp."""

from __future__ import annotations

from tests.fixtures.demo_corp.schema.audit import audit_ddl
from tests.fixtures.demo_corp.schema.auth import auth_ddl
from tests.fixtures.demo_corp.schema.clinical import clinical_ddl
from tests.fixtures.demo_corp.schema.public import public_ddl

__all__ = ["ddl_sections"]


def ddl_sections() -> list[tuple[str, str]]:
    """Return ordered ``(filename, sql)`` pairs for schema creation."""
    return [
        ("00_schemas.sql", _schemas_sql()),
        ("01_tables_public.sql", public_ddl()),
        ("02_tables_clinical.sql", clinical_ddl()),
        ("03_tables_auth.sql", auth_ddl()),
        ("04_tables_audit.sql", audit_ddl()),
        ("05_partitions.sql", _partitions_sql()),
        ("06_constraints.sql", _constraints_sql()),
        ("07_indexes.sql", _indexes_sql()),
        ("08_views.sql", _views_sql()),
    ]


def _schemas_sql() -> str:
    return """\
-- Demo Corp schemas — generated by tests.fixtures.demo_corp.generate
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS clinical CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS audit_internal CASCADE;

CREATE SCHEMA public;
CREATE SCHEMA clinical;
CREATE SCHEMA auth;
CREATE SCHEMA audit_internal;

CREATE EXTENSION IF NOT EXISTS ltree;
"""


def _partitions_sql() -> str:
    months = [
        "2024_01",
        "2024_02",
        "2024_03",
        "2024_04",
        "2024_05",
        "2024_06",
        "2024_07",
        "2024_08",
        "2024_09",
        "2024_10",
        "2024_11",
        "2024_12",
        "2025_01",
        "2025_02",
        "2025_03",
        "2025_04",
        "2025_05",
        "2025_06",
        "2025_07",
        "2025_08",
        "2025_09",
        "2025_10",
        "2025_11",
        "2025_12",
    ]
    lines = ["-- Range partitions for public.raw_events"]
    for _idx, label in enumerate(months):
        year, month = label.split("_")
        start = f"{year}-{month}-01"
        end_year = int(year)
        end_month = int(month) + 1
        if end_month > 12:
            end_month = 1
            end_year += 1
        end = f"{end_year}-{end_month:02d}-01"
        lines.append(
            f"CREATE TABLE public.raw_events_{label} PARTITION OF public.raw_events "
            f"FOR VALUES FROM ('{start}') TO ('{end}');"
        )

    lines.append("")
    lines.append("-- List partitions for clinical.patient_visits")
    for code in ("us_east", "us_west", "us_central", "intl"):
        lines.append(
            f"CREATE TABLE clinical.patient_visits_{code} "
            f"PARTITION OF clinical.patient_visits "
            f"FOR VALUES IN ('{code}');"
        )
    return "\n".join(lines) + "\n"


def _constraints_sql() -> str:
    return """\
-- Deferred FKs breaking the organizations <-> users cycle
ALTER TABLE public.users
    ADD CONSTRAINT users_org_fk
        FOREIGN KEY (org_id) REFERENCES public.organizations (id),
    ADD CONSTRAINT users_manager_fk
        FOREIGN KEY (manager_id) REFERENCES public.users (id);

ALTER TABLE public.organizations
    ADD CONSTRAINT organizations_owner_fk
        FOREIGN KEY (owner_user_id) REFERENCES public.users (id)
        DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT organizations_primary_user_fk
        FOREIGN KEY (primary_user_id) REFERENCES public.users (id)
        DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.subscriptions
    ADD CONSTRAINT subscriptions_org_fk
        FOREIGN KEY (org_id) REFERENCES public.organizations (id);

ALTER TABLE public.invoices
    ADD CONSTRAINT invoices_subscription_fk
        FOREIGN KEY (subscription_id) REFERENCES public.subscriptions (id);

ALTER TABLE public.invoice_line_items
    ADD CONSTRAINT invoice_line_items_invoice_fk
        FOREIGN KEY (invoice_id) REFERENCES public.invoices (id);

ALTER TABLE public.user_addresses
    ADD CONSTRAINT user_addresses_user_fk
        FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.user_payment_methods
    ADD CONSTRAINT user_payment_methods_user_fk
        FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.employees
    ADD CONSTRAINT employees_org_fk
        FOREIGN KEY (org_id) REFERENCES public.organizations (id),
    ADD CONSTRAINT employees_manager_fk
        FOREIGN KEY (manager_id) REFERENCES public.employees (id);

ALTER TABLE public.tickets
    ADD CONSTRAINT tickets_org_fk
        FOREIGN KEY (org_id) REFERENCES public.organizations (id),
    ADD CONSTRAINT tickets_reporter_fk
        FOREIGN KEY (reporter_user_id) REFERENCES public.users (id),
    ADD CONSTRAINT tickets_assigned_fk
        FOREIGN KEY (assigned_to_user_id) REFERENCES public.users (id);

ALTER TABLE public.ticket_messages
    ADD CONSTRAINT ticket_messages_ticket_fk
        FOREIGN KEY (ticket_id) REFERENCES public.tickets (id),
    ADD CONSTRAINT ticket_messages_author_fk
        FOREIGN KEY (author_user_id) REFERENCES public.users (id);

ALTER TABLE public.comments
    ADD CONSTRAINT comments_author_fk
        FOREIGN KEY (author_user_id) REFERENCES public.users (id);

ALTER TABLE clinical.providers
    ADD CONSTRAINT providers_org_fk
        FOREIGN KEY (org_id) REFERENCES public.organizations (id);

ALTER TABLE clinical.patients
    ADD CONSTRAINT patients_provider_fk
        FOREIGN KEY (primary_provider_id) REFERENCES clinical.providers (id),
    ADD CONSTRAINT patients_org_fk
        FOREIGN KEY (org_id) REFERENCES public.organizations (id);

ALTER TABLE clinical.patient_visits
    ADD CONSTRAINT visits_patient_fk
        FOREIGN KEY (patient_id) REFERENCES clinical.patients (id),
    ADD CONSTRAINT visits_provider_fk
        FOREIGN KEY (provider_id) REFERENCES clinical.providers (id);

ALTER TABLE clinical.prescriptions
    ADD CONSTRAINT prescriptions_patient_fk
        FOREIGN KEY (patient_id) REFERENCES clinical.patients (id),
    ADD CONSTRAINT prescriptions_provider_fk
        FOREIGN KEY (provider_id) REFERENCES clinical.providers (id);

ALTER TABLE clinical.patient_documents
    ADD CONSTRAINT patient_documents_patient_fk
        FOREIGN KEY (patient_id) REFERENCES clinical.patients (id);

ALTER TABLE auth.sessions
    ADD CONSTRAINT sessions_user_fk
        FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE auth.api_keys
    ADD CONSTRAINT api_keys_user_fk
        FOREIGN KEY (user_id) REFERENCES public.users (id);
"""


def _indexes_sql() -> str:
    return """\
CREATE UNIQUE INDEX patients_name_dob_uq
    ON clinical.patients (first_name, last_name, dob);
"""


def _views_sql() -> str:
    return """\
CREATE VIEW public.active_clinics_v AS
    SELECT id, name FROM public.organizations WHERE billing_email IS NOT NULL;

CREATE VIEW public.monthly_revenue_v AS
    SELECT date_trunc('month', period_start) AS month, sum(total_cents) AS revenue
    FROM public.invoices
    GROUP BY 1;

CREATE MATERIALIZED VIEW public.tickets_open_mv AS
    SELECT id, subject, status FROM public.tickets WHERE status <> 'closed';
"""
