"""Integration tests for pg_dump-style pre-data / data / post-data DDL phases."""

from __future__ import annotations

import time

import asyncpg
import pytest

from privaci.catalog import introspect_catalog
from privaci.config.models import Config, TableConfig
from privaci.errors import PreflightError
from privaci.pipeline.run_lifecycle import open_run, stream_and_finish
from privaci.pipeline.runner import run_masking_pipeline
from privaci.state import ensure_state_schema
from privaci.state.resume import load_checkpoints
from tests.fixtures.constants import TEST_SALT
from tests.integration.catalog_config import config_keep_only

pytestmark = [pytest.mark.integration, pytest.mark.asyncio]

_SCHEMA = "ddl_phases"
_TABLE = f"{_SCHEMA}.items"
_UNIQUE_IDX = "ddl_phases_items_code_uq"
_NONUNIQUE_IDX = "ddl_phases_items_label_idx"
_VIEW = "items_v"
_TRIGGER = "items_audit_noop"
_FN = "items_audit_noop"


async def _reset_source(conn: asyncpg.Connection) -> None:
    await conn.execute(f'DROP SCHEMA IF EXISTS "{_SCHEMA}" CASCADE')
    await conn.execute(f'CREATE SCHEMA "{_SCHEMA}"')
    await conn.execute(f"""
        CREATE TABLE "{_SCHEMA}".items (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            code text NOT NULL,
            label text NOT NULL
        )
        """)
    await conn.execute(f"""
        CREATE UNIQUE INDEX {_UNIQUE_IDX}
            ON "{_SCHEMA}".items (code)
        """)
    await conn.execute(f"""
        CREATE INDEX {_NONUNIQUE_IDX}
            ON "{_SCHEMA}".items (label)
        """)
    await conn.execute(f"""
        CREATE OR REPLACE FUNCTION "{_SCHEMA}".{_FN}()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RETURN NEW;
        END;
        $$
        """)
    await conn.execute(f"""
        CREATE TRIGGER {_TRIGGER}
            AFTER INSERT ON "{_SCHEMA}".items
            FOR EACH ROW
            EXECUTE FUNCTION "{_SCHEMA}".{_FN}()
        """)
    # security_invoker so the view is not elevated (no elevated_objects entry).
    # Fixed fixture identifiers only.
    await conn.execute(f"""
        CREATE VIEW "{_SCHEMA}".{_VIEW}
            WITH (security_invoker = true) AS
        SELECT id, code, label FROM "{_SCHEMA}".items
        """)  # noqa: S608
    await conn.execute(f"""
        INSERT INTO "{_SCHEMA}".items (code, label)
        VALUES ('a1', 'alpha'), ('b2', 'beta')
        """)  # noqa: S608


async def _drop_source(conn: asyncpg.Connection) -> None:
    await conn.execute(f'DROP SCHEMA IF EXISTS "{_SCHEMA}" CASCADE')


@pytest.fixture
async def ddl_phases_source(source_dsn: str):
    conn = await asyncpg.connect(source_dsn)
    try:
        await _reset_source(conn)
    finally:
        await conn.close()
    yield
    conn = await asyncpg.connect(source_dsn)
    try:
        await _drop_source(conn)
    finally:
        await conn.close()


async def _config(source_dsn: str, **updates: object) -> Config:
    """Scope config to ddl_phases.items; skip any elevated objects on the source."""
    defaults: dict[str, object] = {
        "auto_detect": False,
        "replicate_views": True,
        "replicate_functions": True,
        "replicate_all_indexes": True,
        "replicate_triggers": True,
    }
    defaults.update(updates)
    return await config_keep_only(
        source_dsn,
        {_TABLE: TableConfig()},
        **defaults,
    )


async def _index_exists(
    conn: asyncpg.Connection, schema_name: str, index_name: str
) -> bool:
    found = await conn.fetchval(
        """
        SELECT EXISTS (
            SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind = 'i'
        )
        """,
        schema_name,
        index_name,
    )
    return bool(found)


async def _view_exists(conn: asyncpg.Connection) -> bool:
    found = await conn.fetchval(
        """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.views
            WHERE table_schema = $1 AND table_name = $2
        )
        """,
        _SCHEMA,
        _VIEW,
    )
    return bool(found)


async def _trigger_exists(conn: asyncpg.Connection) -> bool:
    found = await conn.fetchval(
        """
        SELECT EXISTS (
            SELECT 1
            FROM pg_trigger t
            JOIN pg_class c ON c.oid = t.tgrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = $1 AND c.relname = 'items' AND t.tgname = $2
        )
        """,
        _SCHEMA,
        _TRIGGER,
    )
    return bool(found)


async def test_unique_pre_data_nonunique_and_views_post_data(
    source_dsn: str,
    target_dsn: str,
    ddl_phases_source: None,
    clean_target: None,
) -> None:
    """Unique indexes pre-stream; views/non-unique/triggers only after post-data."""
    config = await _config(source_dsn)
    source = await asyncpg.connect(source_dsn)
    target = await asyncpg.connect(target_dsn)
    started_at = time.monotonic()
    try:
        catalog = await introspect_catalog(source)
        await ensure_state_schema(target)
        run_id, audit = await open_run(
            target,
            catalog,
            config,
            source_dsn=source_dsn,
            salt=TEST_SALT,
            resume_run_id=None,
            audit_enabled=True,
        )

        assert await _index_exists(target, _SCHEMA, _UNIQUE_IDX)
        assert not await _index_exists(target, _SCHEMA, _NONUNIQUE_IDX)
        assert not await _view_exists(target)
        assert not await _trigger_exists(target)

        await stream_and_finish(
            source,
            target,
            catalog,
            config,
            TEST_SALT,
            run_id,
            audit,
            started_at,
            source_dsn=source_dsn,
            checkpoints=None,
        )

        assert await _index_exists(target, _SCHEMA, _UNIQUE_IDX)
        assert await _index_exists(target, _SCHEMA, _NONUNIQUE_IDX)
        assert await _view_exists(target)
        assert await _trigger_exists(target)

        post_trigger = await target.fetchval(
            """
            SELECT count(*)::int
            FROM _privaci.audit_log
            WHERE event_type = 'created_object'
              AND table_name = 'items'
              AND payload->>'kind' = 'trigger'
              AND payload->>'object_name' = $1
              AND payload->>'ddl_phase' = 'post-data'
            """,
            _TRIGGER,
        )
        assert int(post_trigger or 0) == 1
    finally:
        await source.close()
        await target.close()


async def test_replicate_triggers_false_skips_trigger(
    source_dsn: str,
    target_dsn: str,
    ddl_phases_source: None,
    clean_target: None,
) -> None:
    """``replicate_triggers: false`` leaves triggers absent and audits skip."""
    config = await _config(source_dsn, replicate_triggers=False)
    await run_masking_pipeline(
        source_dsn, target_dsn, config, TEST_SALT, audit_enabled=True
    )

    target = await asyncpg.connect(target_dsn)
    try:
        assert not await _trigger_exists(target)
        skipped = await target.fetchval(
            """
            SELECT count(*)::int
            FROM _privaci.audit_log
            WHERE event_type = 'skipped_object'
              AND table_name = 'items'
              AND payload->>'kind' = 'trigger'
              AND payload->>'object_name' = $1
              AND payload->>'reason' = 'flag_disabled'
            """,
            _TRIGGER,
        )
        assert int(skipped or 0) == 1
        assert await _view_exists(target)
    finally:
        await target.close()


async def test_resume_completes_post_data_without_restream(
    source_dsn: str,
    target_dsn: str,
    ddl_phases_source: None,
    clean_target: None,
    mocker: pytest.MockFixture,
) -> None:
    """Failed post-data leaves run failed; resume finishes DDL without re-stream."""
    config = await _config(source_dsn)
    real_apply = __import__(
        "privaci.schema.post_data", fromlist=["apply_post_data_ddl"]
    ).apply_post_data_ddl
    calls = {"n": 0}

    async def _fail_first(
        *args: object, **kwargs: object
    ) -> tuple[tuple[object, ...], tuple[tuple[str, str], ...]]:
        calls["n"] += 1
        if calls["n"] == 1:
            raise PreflightError(
                "Applying post-data schema DDL on the target database",
                cause="simulated post-data failure",
                remediation="resume after the fault is cleared",
            )
        return await real_apply(*args, **kwargs)

    mocker.patch(
        "privaci.pipeline.run_lifecycle.apply_post_data_ddl",
        side_effect=_fail_first,
    )

    with pytest.raises(PreflightError, match="simulated post-data failure"):
        await run_masking_pipeline(
            source_dsn, target_dsn, config, TEST_SALT, audit_enabled=True
        )

    target = await asyncpg.connect(target_dsn)
    try:
        failed = await target.fetchrow("""
            SELECT run_id, status FROM _privaci.runs
            WHERE status = 'failed' ORDER BY started_at DESC LIMIT 1
            """)
        assert failed is not None
        run_id = failed["run_id"]
        assert not await _view_exists(target)
        assert not await _trigger_exists(target)
        rows_before = int(
            await target.fetchval(
                f'SELECT count(*)::int FROM "{_SCHEMA}".items'  # noqa: S608
            )
            or 0
        )
        assert rows_before == 2
        checkpoints = await load_checkpoints(target, run_id)
        assert all(cp.status.value == "done" for cp in checkpoints.values())
    finally:
        await target.close()

    resumed = await run_masking_pipeline(
        source_dsn,
        target_dsn,
        config,
        TEST_SALT,
        audit_enabled=True,
        resume_run_id=run_id,
        checkpoints=checkpoints,
    )
    assert resumed.rows_processed == 0

    target = await asyncpg.connect(target_dsn)
    try:
        assert await _view_exists(target)
        assert await _trigger_exists(target)
        assert await _index_exists(target, _SCHEMA, _NONUNIQUE_IDX)
        rows_after = int(
            await target.fetchval(
                f'SELECT count(*)::int FROM "{_SCHEMA}".items'  # noqa: S608
            )
            or 0
        )
        assert rows_after == 2
        status = await target.fetchval(
            "SELECT status FROM _privaci.runs WHERE run_id = $1",
            run_id,
        )
        assert status == "succeeded"
    finally:
        await target.close()
