"""Integration: CEL ``when:`` masks only matching rows on a live Postgres path."""

from __future__ import annotations

import json

import asyncpg
import pytest

from privaci.config.actions import StaticAction
from privaci.config.models import TableConfig
from privaci.pipeline.runner import run_masking_pipeline
from tests.fixtures.constants import TEST_SALT
from tests.integration.catalog_config import config_keep_only

pytestmark = [pytest.mark.integration, pytest.mark.asyncio]

_SCHEMA = "cel_when"
_TABLE = f"{_SCHEMA}.tickets"


async def _reset_source(conn: asyncpg.Connection) -> None:
    await conn.execute(f'DROP SCHEMA IF EXISTS "{_SCHEMA}" CASCADE')
    await conn.execute(f'CREATE SCHEMA "{_SCHEMA}"')
    await conn.execute(f"""
        CREATE TABLE "{_SCHEMA}".tickets (
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            status text NOT NULL,
            notes text NOT NULL
        )
        """)
    await conn.execute(f"""
        INSERT INTO "{_SCHEMA}".tickets (status, notes)
        VALUES
            ('open', 'keep-open'),
            ('closed', 'secret-closed'),
            ('open', 'keep-open-2')
        """)  # noqa: S608


async def _drop_source(conn: asyncpg.Connection) -> None:
    await conn.execute(f'DROP SCHEMA IF EXISTS "{_SCHEMA}" CASCADE')


@pytest.fixture
async def cel_when_source(source_dsn: str):
    conn = await asyncpg.connect(source_dsn)
    try:
        await _reset_source(conn)
    finally:
        await conn.close()
    yield
    conn = await asyncpg.connect(source_dsn)
    try:
        await _drop_source(conn)
    finally:
        await conn.close()


async def test_when_masks_only_closed_rows(
    source_dsn: str,
    target_dsn: str,
    cel_when_source: None,
    clean_target: None,
) -> None:
    """``when: status == 'closed'`` redacts closed notes; open notes pass through."""
    config = await config_keep_only(
        source_dsn,
        {
            _TABLE: TableConfig(
                columns={
                    "notes": StaticAction(
                        action="static",
                        value="REDACTED",
                        when="status == 'closed'",
                    )
                }
            )
        },
        auto_detect=False,
        replicate_views=False,
        replicate_functions=False,
        replicate_triggers=False,
    )

    await run_masking_pipeline(
        config=config,
        source_dsn=source_dsn,
        target_dsn=target_dsn,
        salt=TEST_SALT,
    )

    target = await asyncpg.connect(target_dsn)
    try:
        rows = await target.fetch(f"""
            SELECT status, notes
            FROM "{_SCHEMA}".tickets
            ORDER BY id
            """)  # noqa: S608
        by_status = [(r["status"], r["notes"]) for r in rows]
        assert ("open", "keep-open") in by_status
        assert ("open", "keep-open-2") in by_status
        assert ("closed", "REDACTED") in by_status
        assert all(
            notes != "secret-closed" for _, notes in by_status
        ), "source secret must not appear on target"

        skip_audits = await target.fetch(
            """
            SELECT column_name, payload
            FROM _privaci.audit_log
            WHERE event_type = 'column.conditional_skip'
              AND schema_name = $1
              AND table_name = 'tickets'
            """,
            _SCHEMA,
        )
        assert len(skip_audits) == 1
        raw = skip_audits[0]["payload"]
        payload = raw if isinstance(raw, dict) else json.loads(raw)
        assert skip_audits[0]["column_name"] == "notes"
        assert payload["skipped_rows"] == 2
        assert payload["evaluated_rows"] == 3
        assert "expression_hash" in payload
        assert "secret" not in str(payload).lower()
    finally:
        await target.close()
