"""Tests for DDL emission from catalog metadata."""

from __future__ import annotations

from privaci.catalog.models import (
    CheckConstraintInfo,
    ColumnInfo,
    ForeignKeyInfo,
    IndexInfo,
    TableInfo,
)
from privaci.schema.ddl import (
    emit_create_schema,
    emit_create_sequence,
    emit_create_table,
    emit_foreign_key,
    emit_unique_indexes,
)


def _sample_table() -> TableInfo:
    return TableInfo(
        schema_name="public",
        table_name="users",
        columns=(
            ColumnInfo(
                name="id",
                data_type="integer",
                not_null=True,
                is_identity=True,
                identity_generation="BY DEFAULT",
            ),
            ColumnInfo(name="email", data_type="text", not_null=True),
        ),
        primary_key=("id",),
        check_constraints=(
            CheckConstraintInfo(name="users_email_chk", definition="email <> ''"),
        ),
        indexes=(
            IndexInfo(
                name="users_email_key",
                is_unique=True,
                definition=(
                    'CREATE UNIQUE INDEX "users_email_key" ' "ON public.users (email)"
                ),
                columns=("email",),
            ),
            IndexInfo(
                name="users_email_idx",
                is_unique=False,
                definition='CREATE INDEX "users_email_idx" ON public.users (email)',
                columns=("email",),
            ),
        ),
    )


def test_emit_create_schema() -> None:
    # Act
    sql = emit_create_schema("clinical")

    # Assert
    assert 'CREATE SCHEMA IF NOT EXISTS "clinical"' in sql


def test_emit_create_table_includes_pk_and_checks() -> None:
    # Act
    sql = emit_create_table(_sample_table())

    # Assert
    assert 'CREATE TABLE IF NOT EXISTS "public"."users"' in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "PRIMARY KEY" in sql
    assert "users_email_chk" in sql


def test_emit_unique_indexes_honors_replicate_all_flag() -> None:
    # Arrange
    table = _sample_table()

    # Act
    unique_only = emit_unique_indexes(table, replicate_all=False)
    all_indexes = emit_unique_indexes(table, replicate_all=True)

    # Assert
    assert len(unique_only) == 1
    assert len(all_indexes) == 2


def test_emit_create_sequence_embeds_regclass_ready_name() -> None:
    # pg_get_serial_sequence already returns a regclass-ready qualified name.
    # Act
    sql = emit_create_sequence("public.users_id_seq")

    # Assert
    assert sql == "CREATE SEQUENCE IF NOT EXISTS public.users_id_seq"


def test_emit_create_sequence_preserves_dotted_quoted_identifier() -> None:
    # A schema or sequence name legitimately containing a dot arrives already
    # quoted; it must be embedded verbatim, not split on "." and corrupted.
    # Act
    sql = emit_create_sequence('"my.schema"."my.seq"')

    # Assert
    assert sql == 'CREATE SEQUENCE IF NOT EXISTS "my.schema"."my.seq"'


def test_emit_create_table_preserves_generated_always_identity() -> None:
    # Arrange
    table = TableInfo(
        schema_name="clinical",
        table_name="patients",
        columns=(
            ColumnInfo(
                name="id",
                data_type="bigint",
                not_null=True,
                is_identity=True,
                identity_generation="ALWAYS",
                sequence_name="clinical.patients_id_seq",
            ),
        ),
        primary_key=("id",),
    )

    # Act
    sql = emit_create_table(table)

    # Assert
    assert "GENERATED ALWAYS AS IDENTITY" in sql


def test_emit_create_table_emits_serial_default() -> None:
    # Arrange
    table = TableInfo(
        schema_name="public",
        table_name="legacy_users",
        columns=(
            ColumnInfo(
                name="id",
                data_type="integer",
                not_null=True,
                uses_serial=True,
                sequence_name="public.legacy_users_id_seq",
            ),
        ),
        primary_key=("id",),
    )

    # Act
    sql = emit_create_table(table)

    # Assert
    assert "DEFAULT nextval('public.legacy_users_id_seq'::regclass)" in sql
    assert "GENERATED" not in sql


def test_emit_foreign_key_includes_deferrable_clause() -> None:
    # Arrange
    table = _sample_table()
    fk = ForeignKeyInfo(
        name="users_org_fk",
        source_columns=("org_id",),
        referenced_schema="public",
        referenced_table="orgs",
        referenced_columns=("id",),
        on_delete="CASCADE",
        on_update="NO ACTION",
        deferrable=True,
        initially_deferred=True,
    )

    # Act
    sql = emit_foreign_key(table, fk)

    # Assert
    assert "DEFERRABLE INITIALLY DEFERRED" in sql
    assert "ON DELETE CASCADE" in sql
