-- Synthetic evaluation seed (~sub-MB). No real PII — example.test emails only.

CREATE TABLE IF NOT EXISTS public.organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id bigint NOT NULL REFERENCES public.organizations (id),
    email text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    phone text
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON public.users (email);
