"""Tests for mask-rules scaffold generation."""

from __future__ import annotations

from privaci.catalog.models import (
    CatalogResult,
    ColumnInfo,
    LoadLayer,
    LoadPlan,
    TableInfo,
)
from privaci.config import load_config
from privaci.config.export_yaml import export_config_yaml
from privaci.config.scaffold import build_scaffold_config
from tests.fixtures.constants import SUPPORTED_CONFIG_VERSION


def _table(
    schema: str,
    name: str,
    columns: tuple[ColumnInfo, ...],
    *,
    primary_key: tuple[str, ...] = ("id",),
) -> TableInfo:
    return TableInfo(
        schema_name=schema,
        table_name=name,
        columns=columns,
        primary_key=primary_key,
    )


def _catalog(*tables: TableInfo) -> CatalogResult:
    table_map = {table.identifier: table for table in tables}
    return CatalogResult(
        tables=table_map,
        load_plan=LoadPlan(layers=(LoadLayer(table_ids=tuple(table_map)),)),
    )


def test_build_scaffold_includes_high_confidence_email(tmp_path) -> None:
    # Arrange
    users = _table(
        "public",
        "users",
        (
            ColumnInfo(name="id", data_type="integer", not_null=True),
            ColumnInfo(name="email", data_type="text", not_null=True),
        ),
    )
    catalog = _catalog(users)

    # Act
    result = build_scaffold_config(catalog)
    yaml_text = export_config_yaml(result.config, init_header=True)
    path = tmp_path / "mask-rules.yaml"
    path.write_text(yaml_text, encoding="utf-8")
    loaded = load_config(path)

    # Assert
    assert loaded.version == SUPPORTED_CONFIG_VERSION
    assert loaded.global_salt is not None
    assert loaded.global_salt.get_secret_value() == "${ANONYMIZATION_SALT}"
    email_action = loaded.tables["public.users"].columns["email"]
    assert email_action.action == "fake"
    assert email_action.provider == "email"


def test_build_scaffold_excludes_tables_without_primary_key() -> None:
    # Arrange
    audit = _table(
        "audit_internal",
        "audit_log_events",
        (ColumnInfo(name="message", data_type="text", not_null=False),),
        primary_key=(),
    )
    catalog = _catalog(audit)

    # Act
    result = build_scaffold_config(catalog)

    # Assert
    assert result.config.tables["audit_internal.audit_log_events"].strategy == "exclude"


def test_export_yaml_includes_init_header() -> None:
    # Arrange
    users = _table(
        "public",
        "users",
        (ColumnInfo(name="email", data_type="text", not_null=True),),
    )
    result = build_scaffold_config(_catalog(users))

    # Act
    text = export_config_yaml(result.config, init_header=True)

    # Assert
    assert text.startswith("# Generated by privaci init")
    assert "version:" in text
    assert "${ANONYMIZATION_SALT}" in text
