"""Emit CI/CD workflow templates for PrivaCI masking jobs."""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path

from privaci.errors import ConfigError

GITHUB_WORKFLOW = """\
# Generated by `privaci generate-ci --platform github-actions`
name: PrivaCI Refresh

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  mask:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/boundarylogic/privaci:latest
    env:
      SOURCE_DB_URL: ${{ secrets.SOURCE_DB_URL }}
      TARGET_DB_URL: ${{ secrets.TARGET_DB_URL }}
      ANONYMIZATION_SALT: ${{ secrets.ANONYMIZATION_SALT }}
    steps:
      - name: Run masking pipeline
        run: privaci run --config /config/mask-rules.yaml
"""

GITHUB_SETUP_DOC = """\
# PrivaCI GitHub Actions setup

Generated by `privaci generate-ci --platform github-actions`.

## Required repository secrets

| Secret | Description |
|--------|-------------|
| `SOURCE_DB_URL` | Read-only connection string for the source Postgres database |
| `TARGET_DB_URL` | Writable connection string for the masked target database |
| `ANONYMIZATION_SALT` | 64-character hex salt from `privaci gen-salt` |

## Workflow

The workflow `.github/workflows/privaci-refresh.yml` runs weekly (Sunday 03:00 UTC)
and on manual dispatch. Mount or bake `mask-rules.yaml` into the container at
`/config/mask-rules.yaml`, or adjust the `privaci run --config` path.
"""

GITLAB_CI = """\
# Generated by `privaci generate-ci --platform gitlab-ci`
stages:
  - mask

privaci_refresh:
  stage: mask
  image: ghcr.io/boundarylogic/privaci:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    SOURCE_DB_URL: $SOURCE_DB_URL
    TARGET_DB_URL: $TARGET_DB_URL
    ANONYMIZATION_SALT: $ANONYMIZATION_SALT
  script:
    - privaci run --config /config/mask-rules.yaml
"""

K8S_CRONJOB = """\
# Generated by `privaci generate-ci --platform k8s-cronjob`
apiVersion: batch/v1
kind: CronJob
metadata:
  name: privaci-refresh
spec:
  schedule: "0 3 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: privaci
              image: ghcr.io/boundarylogic/privaci:latest
              command: ["privaci", "run", "--config", "/config/mask-rules.yaml"]
              env:
                - name: SOURCE_DB_URL
                  valueFrom:
                    secretKeyRef:
                      name: privaci-secrets
                      key: source-db-url
                - name: TARGET_DB_URL
                  valueFrom:
                    secretKeyRef:
                      name: privaci-secrets
                      key: target-db-url
                - name: ANONYMIZATION_SALT
                  valueFrom:
                    secretKeyRef:
                      name: privaci-secrets
                      key: anonymization-salt
              volumeMounts:
                - name: mask-rules
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: mask-rules
              configMap:
                name: privaci-mask-rules
"""


class CiPlatform(StrEnum):
    """Supported ``generate-ci`` platforms."""

    GITHUB_ACTIONS = "github-actions"
    GITLAB_CI = "gitlab-ci"
    K8S_CRONJOB = "k8s-cronjob"


def generate_ci_files(platform: str, *, output_dir: Path | None = None) -> list[Path]:
    """Write CI templates for ``platform`` and return the paths created."""
    try:
        selected = CiPlatform(platform)
    except ValueError as exc:
        raise ConfigError(
            "Generating CI workflow files",
            cause=f"Unknown platform {platform!r}.",
            remediation=("Use one of: github-actions, gitlab-ci, k8s-cronjob."),
        ) from exc

    root = output_dir or Path.cwd()
    if selected is CiPlatform.GITHUB_ACTIONS:
        workflow = root / ".github" / "workflows" / "privaci-refresh.yml"
        workflow.parent.mkdir(parents=True, exist_ok=True)
        workflow.write_text(GITHUB_WORKFLOW, encoding="utf-8")
        setup = root / "docs" / "privaci-setup.md"
        setup.parent.mkdir(parents=True, exist_ok=True)
        setup.write_text(GITHUB_SETUP_DOC, encoding="utf-8")
        return [workflow, setup]

    if selected is CiPlatform.GITLAB_CI:
        target = root / ".gitlab-ci.yml"
        target.write_text(GITLAB_CI, encoding="utf-8")
        return [target]

    target = root / "privaci-cronjob.yaml"
    target.write_text(K8S_CRONJOB, encoding="utf-8")
    return [target]
