"""Serialize a validated :class:`Config` to mask-rules.yaml text."""

from __future__ import annotations

import yaml

from privaci.config.models import Config
from privaci.secrets.types import SecretStr

_INIT_HEADER = (
    "# Generated by privaci init — review before production run.\n"
    "# See docs/configuration.md and run: privaci plan --config <this-file>\n\n"
)


def export_config_yaml(config: Config, *, init_header: bool = False) -> str:
    """Dump ``config`` as YAML suitable for ``load_config``.

    Args:
        config: Validated configuration document.
        init_header: When ``True``, prepend the standard init review banner.

    Returns:
        UTF-8 YAML text with a trailing newline.
    """
    payload = _config_to_mapping(config)
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    prefix = _INIT_HEADER if init_header else ""
    return f"{prefix}{body}"


def _config_to_mapping(config: Config) -> dict[str, object]:
    """Convert config to a YAML-friendly dict without secret wrappers."""
    data = config.model_dump(mode="json")
    data["global_salt"] = _secret_literal(config.global_salt)
    data["pseudonym_key"] = _secret_literal(config.pseudonym_key)
    return data


def _secret_literal(value: SecretStr | None) -> str | None:
    if value is None:
        return None
    text = value.get_secret_value()
    return text if text else None
