#!/usr/bin/env python3
"""Generate reference docs from live code (JSON Schema + Typer).

Writes:
  docs/generated/mask-rules.schema.json
  docs/generated/configuration-reference.md
  docs/generated/cli-reference.md

Usage:
  python scripts/generate_docs.py          # write files
  python scripts/generate_docs.py --check  # exit 1 if outputs are stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import click
from typer.main import get_command

from privaci.cli.app import app
from privaci.config.loader import export_json_schema

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "docs" / "generated"

_HEADER = "<!-- AUTO-GENERATED by scripts/generate_docs.py — do not edit by hand. -->\n"


def _type_label(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    """Render a JSON Schema fragment as a short type string."""
    if "$ref" in schema:
        ref = schema["$ref"].removeprefix("#/$defs/")
        return f"[{ref}](#{ref.lower()})"
    if "anyOf" in schema:
        parts = [_type_label(item, defs) for item in schema["anyOf"]]
        return " \\| ".join(parts)
    if "enum" in schema:
        return "enum: " + ", ".join(f"`{v}`" for v in schema["enum"])
    if schema.get("type") == "array":
        items = schema.get("items", {})
        return f"array[{_type_label(items, defs)}]"
    if schema.get("type") == "object":
        return "object"
    if schema.get("type"):
        return str(schema["type"])
    return "any"


def _props_table(
    properties: dict[str, Any],
    defs: dict[str, Any],
    *,
    required: set[str],
) -> list[str]:
    """Build a markdown table for a property map."""
    lines = [
        "| Field | Type | Required | Description |",
        "|-------|------|----------|-------------|",
    ]
    for name, prop in sorted(properties.items()):
        desc = prop.get("description", "").replace("\n", " ")
        req = "yes" if name in required else "no"
        default = prop.get("default")
        default_note = f" Default: `{default}`." if default is not None else ""
        lines.append(
            f"| `{name}` | {_type_label(prop, defs)} | {req} | {desc}{default_note} |"
        )
    return lines


def _render_schema_markdown(schema: dict[str, Any]) -> str:
    """Turn the mask-rules JSON Schema into a reference page."""
    defs: dict[str, Any] = schema.get("$defs", {})
    root_props = schema.get("properties", {})
    root_required = set(schema.get("required", []))

    lines = [
        _HEADER.rstrip(),
        "# Configuration reference (auto-generated)",
        "",
        "Generated from the pydantic ``Config`` model. For narrative examples",
        "see [`configuration.md`](../configuration.md). Raw schema:",
        "[`mask-rules.schema.json`](mask-rules.schema.json).",
        "",
        "Regenerate with ``make docs-generate``.",
        "",
        "## Root document (`mask-rules.yaml`)",
        "",
        *_props_table(root_props, defs, required=root_required),
        "",
    ]

    for def_name, def_schema in sorted(defs.items()):
        props = def_schema.get("properties", {})
        if not props:
            continue
        required = set(def_schema.get("required", []))
        lines.extend(
            [
                f"## `{def_name}`",
                "",
                *_props_table(props, defs, required=required),
                "",
            ]
        )
    return "\n".join(lines)


def _option_rows(command: click.Command) -> list[str]:
    """Extract markdown table rows for a command's options."""
    rows: list[str] = []
    for param in command.params:
        if not isinstance(param, click.Option):
            continue
        names = ", ".join(f"`{opt}`" for opt in param.opts)
        env = f"`{param.envvar}`" if param.envvar else "—"
        default = "—" if param.default is None else f"`{param.default}`"
        help_text = (param.help or "").replace("\n", " ")
        rows.append(f"| {names} | {env} | {default} | {help_text} |")
    return rows


def _append_command(
    lines: list[str],
    command: click.Command,
    qualified_name: str,
    *,
    is_root: bool = False,
) -> None:
    """Recursively append CLI reference sections for a Click command tree."""
    if isinstance(command, click.Group):
        if command.callback:
            doc = (command.help or "").strip()
            label = (
                f"`{qualified_name}` (default)" if is_root else f"`{qualified_name}`"
            )
            lines.extend([f"## {label}", ""])
            if doc:
                lines.extend([doc, ""])
            option_rows = _option_rows(command)
            if option_rows:
                lines.extend(
                    [
                        "| Option | Env var | Default | Description |",
                        "|--------|---------|---------|-------------|",
                        *option_rows,
                        "",
                    ]
                )
        for sub_name in sorted(command.commands):
            sub = command.commands[sub_name]
            sub_qualified = f"{qualified_name} {sub_name}".strip()
            _append_command(lines, sub, sub_qualified)
        return

    lines.extend([f"## `{qualified_name}`", ""])
    if command.help:
        lines.extend([command.help.strip(), ""])
    option_rows = _option_rows(command)
    if option_rows:
        lines.extend(
            [
                "| Option | Env var | Default | Description |",
                "|--------|---------|---------|-------------|",
                *option_rows,
                "",
            ]
        )


def _render_cli_markdown() -> str:
    """Build the CLI reference from the Typer application."""
    lines = [
        _HEADER.rstrip(),
        "# CLI reference (auto-generated)",
        "",
        "Generated from ``src/privaci/cli/app.py``. For copy-pasteable",
        "examples see [`cli-reference.md`](../cli-reference.md).",
        "",
        "Regenerate with ``make docs-generate``.",
        "",
        "Invoking ``privaci`` with no subcommand runs ``privaci run``.",
        "",
    ]
    root = get_command(app)
    _append_command(lines, root, "privaci", is_root=True)
    return "\n".join(lines) + "\n"


def _outputs() -> dict[Path, str]:
    """Compute all generated file paths and contents."""
    schema_json = export_json_schema()
    schema = json.loads(schema_json)
    return {
        GENERATED / "mask-rules.schema.json": schema_json + "\n",
        GENERATED / "configuration-reference.md": _render_schema_markdown(schema),
        GENERATED / "cli-reference.md": _render_cli_markdown(),
    }


def _write_outputs(outputs: dict[Path, str]) -> None:
    """Write generated documentation files to disk."""
    GENERATED.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")


def _check_outputs(outputs: dict[Path, str]) -> list[Path]:
    """Return paths whose on-disk content differs from expected."""
    stale: list[Path] = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
    return stale


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint for doc generation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files are missing or out of date.",
    )
    args = parser.parse_args(argv)
    outputs = _outputs()

    if args.check:
        stale = _check_outputs(outputs)
        if stale:
            names = ", ".join(str(p.relative_to(ROOT)) for p in stale)
            print(f"Stale generated docs: {names}", file=sys.stderr)
            print("Run: make docs-generate", file=sys.stderr)
            return 1
        return 0

    _write_outputs(outputs)
    for path in outputs:
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
