#!/usr/bin/env python3
"""Generate reference docs from live code (JSON Schema + Typer).

Writes:
  docs/generated/mask-rules.schema.json
  docs/generated/configuration-reference.md
  docs/generated/cli-reference.md
  docs/generated/errors/*.md
  docs/generated/configuration/*.md

Usage:
  python scripts/generate_docs.py          # write files
  python scripts/generate_docs.py --check  # exit 1 if outputs are stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import click
from typer.main import get_command

from privaci.cli.app import app
from privaci.config.loader import export_json_schema

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "docs" / "generated"
ERROR_CODES_SOURCE = ROOT / "docs" / "error-codes.md"
ERRORS_DIR = GENERATED / "errors"
CONFIG_TYPES_DIR = GENERATED / "configuration"

_HEADER = "<!-- AUTO-GENERATED by scripts/generate_docs.py — do not edit by hand. -->\n"


def _type_label(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    """Render a JSON Schema fragment as a short type string."""
    if "$ref" in schema:
        ref = schema["$ref"].removeprefix("#/$defs/")
        return f"[{ref}](#{ref.lower()})"
    if "anyOf" in schema:
        parts = [_type_label(item, defs) for item in schema["anyOf"]]
        return " \\| ".join(parts)
    if "enum" in schema:
        return "enum: " + ", ".join(f"`{v}`" for v in schema["enum"])
    if schema.get("type") == "array":
        items = schema.get("items", {})
        return f"array[{_type_label(items, defs)}]"
    if schema.get("type") == "object":
        return "object"
    if schema.get("type"):
        return str(schema["type"])
    return "any"


def _props_table(
    properties: dict[str, Any],
    defs: dict[str, Any],
    *,
    required: set[str],
) -> list[str]:
    """Build a markdown table for a property map."""
    lines = [
        "| Field | Type | Required | Description |",
        "|-------|------|----------|-------------|",
    ]
    for name, prop in sorted(properties.items()):
        desc = prop.get("description", "").replace("\n", " ")
        req = "yes" if name in required else "no"
        default = prop.get("default")
        default_note = f" Default: `{default}`." if default is not None else ""
        lines.append(
            f"| `{name}` | {_type_label(prop, defs)} | {req} | {desc}{default_note} |"
        )
    return lines


def _render_schema_markdown(schema: dict[str, Any]) -> str:
    """Turn the mask-rules JSON Schema into a reference page."""
    defs: dict[str, Any] = schema.get("$defs", {})
    root_props = schema.get("properties", {})
    root_required = set(schema.get("required", []))

    lines = [
        _HEADER.rstrip(),
        "# Configuration reference (auto-generated)",
        "",
        "Generated from the pydantic ``Config`` model. For narrative examples",
        "see [`configuration.md`](../configuration.md). Raw schema:",
        "[`mask-rules.schema.json`](mask-rules.schema.json).",
        "",
        "Regenerate with ``make docs-generate``.",
        "",
        "## Root document (`mask-rules.yaml`)",
        "",
        *_props_table(root_props, defs, required=root_required),
        "",
    ]

    for def_name, def_schema in sorted(defs.items()):
        props = def_schema.get("properties", {})
        if not props:
            continue
        required = set(def_schema.get("required", []))
        lines.extend(
            [
                f"## `{def_name}`",
                "",
                *_props_table(props, defs, required=required),
                "",
            ]
        )
    return "\n".join(lines)


def _option_rows(command: click.Command) -> list[str]:
    """Extract markdown table rows for a command's options."""
    rows: list[str] = []
    for param in command.params:
        if not isinstance(param, click.Option):
            continue
        names = ", ".join(f"`{opt}`" for opt in param.opts)
        env = f"`{param.envvar}`" if param.envvar else "—"
        default = "—" if param.default is None else f"`{param.default}`"
        help_text = (param.help or "").replace("\n", " ")
        rows.append(f"| {names} | {env} | {default} | {help_text} |")
    return rows


def _append_command(
    lines: list[str],
    command: click.Command,
    qualified_name: str,
    *,
    is_root: bool = False,
) -> None:
    """Recursively append CLI reference sections for a Click command tree."""
    if isinstance(command, click.Group):
        if command.callback:
            doc = (command.help or "").strip()
            label = (
                f"`{qualified_name}` (default)" if is_root else f"`{qualified_name}`"
            )
            lines.extend([f"## {label}", ""])
            if doc:
                lines.extend([doc, ""])
            option_rows = _option_rows(command)
            if option_rows:
                lines.extend(
                    [
                        "| Option | Env var | Default | Description |",
                        "|--------|---------|---------|-------------|",
                        *option_rows,
                        "",
                    ]
                )
        for sub_name in sorted(command.commands):
            sub = command.commands[sub_name]
            sub_qualified = f"{qualified_name} {sub_name}".strip()
            _append_command(lines, sub, sub_qualified)
        return

    lines.extend([f"## `{qualified_name}`", ""])
    if command.help:
        lines.extend([command.help.strip(), ""])
    option_rows = _option_rows(command)
    if option_rows:
        lines.extend(
            [
                "| Option | Env var | Default | Description |",
                "|--------|---------|---------|-------------|",
                *option_rows,
                "",
            ]
        )


def _render_cli_markdown() -> str:
    """Build the CLI reference from the Typer application."""
    lines = [
        _HEADER.rstrip(),
        "# CLI reference (auto-generated)",
        "",
        "Generated from ``src/privaci/cli/app.py``. For copy-pasteable",
        "examples see [`cli-reference.md`](../cli-reference.md).",
        "",
        "Regenerate with ``make docs-generate``.",
        "",
        "Invoking ``privaci`` with no subcommand runs ``privaci run``.",
        "",
    ]
    root = get_command(app)
    _append_command(lines, root, "privaci", is_root=True)
    return "\n".join(lines) + "\n"


def _anchor_from_error_heading(heading_line: str) -> str:
    """Build a stable anchor slug matching ``docs/error-codes.md`` permalinks."""
    text = heading_line.removeprefix("## ").strip()
    text = re.sub(r"\s+\([^)]+\)$", "", text)
    slug = text.lower().replace(": ", "-")
    slug = slug.replace("/", " ")
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    return re.sub(r"\s+", "-", slug.strip())


def _parse_error_code_sections(source: str) -> list[tuple[str, str, str]]:
    """Split ``error-codes.md`` into per-exit-code sections for indexable pages."""
    sections: list[tuple[str, str, str]] = []
    lines = source.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.startswith("## Exit code"):
            index += 1
            continue
        heading = line.removeprefix("## ").strip()
        anchor = _anchor_from_error_heading(line)
        body: list[str] = []
        index += 1
        while index < len(lines):
            next_line = lines[index]
            if next_line.startswith("## Exit code") or next_line.startswith(
                "## 3. Quick reference"
            ):
                break
            body.append(next_line)
            index += 1
        sections.append((anchor, heading, "\n".join(body).strip()))
    return sections


def _fix_relative_doc_links(body: str) -> str:
    """Rewrite sibling doc links for pages under ``docs/generated/``."""
    return re.sub(
        r"\]\((?!https?://|/|\.\./)([\w./-]+\.md)(#[\w-]+)?\)",
        r"](../../\1\2)",
        body,
    )


def _render_error_page(anchor: str, heading: str, body: str) -> str:
    """Render one SEO-friendly exit-code page."""
    code_match = re.search(r"Exit code (\d+)", heading)
    code_label = code_match.group(1) if code_match else heading
    description = (
        f"PrivaCI exit code {code_label}: operator causes, remediation steps, "
        "and CI branching guidance."
    )
    fixed_body = _fix_relative_doc_links(body)
    return (
        f"---\n"
        f'title: "{heading}"\n'
        f'description: "{description}"\n'
        f"---\n\n"
        f"{_HEADER}"
        f"[← Error codes catalogue](../../error-codes.md) · "
        f"[All exit codes](index.md)\n\n"
        f"# {heading}\n\n"
        f"{fixed_body}\n"
    )


def _render_error_index(sections: list[tuple[str, str, str]]) -> str:
    """Render the exit-code index listing every generated page."""
    lines = [
        _HEADER.rstrip(),
        "# Exit codes (index)",
        "",
        "One page per exit code for search and deep linking. The full catalogue",
        "with message format rules lives in",
        "[`error-codes.md`](../../error-codes.md).",
        "",
        "| Code | Page |",
        "|------|------|",
    ]
    for anchor, heading, _ in sections:
        code_match = re.search(r"Exit code (\d+)", heading)
        code = code_match.group(1) if code_match else "—"
        lines.append(f"| `{code}` | [{heading}]({anchor}.md) |")
    lines.append("")
    return "\n".join(lines)


def _render_error_pages() -> dict[Path, str]:
    """Generate indexable markdown pages from ``docs/error-codes.md``."""
    source = ERROR_CODES_SOURCE.read_text(encoding="utf-8")
    sections = _parse_error_code_sections(source)
    outputs: dict[Path, str] = {
        ERRORS_DIR / "index.md": _render_error_index(sections),
    }
    for anchor, heading, body in sections:
        outputs[ERRORS_DIR / f"{anchor}.md"] = _render_error_page(
            anchor, heading, body
        )
    return outputs


def _render_config_type_page(
    def_name: str,
    def_schema: dict[str, Any],
    defs: dict[str, Any],
) -> str:
    """Render one indexable page for a JSON Schema ``$defs`` block."""
    props = def_schema.get("properties", {})
    required = set(def_schema.get("required", []))
    description = (
        f"mask-rules.yaml `{def_name}` schema: fields, types, and defaults "
        "for PrivaCI configuration."
    )
    lines = [
        "---",
        f'title: "Configuration: {def_name}"',
        f'description: "{description}"',
        "---",
        "",
        _HEADER.rstrip(),
        f"# `{def_name}`",
        "",
        "Part of the auto-generated configuration schema. Narrative examples:",
        "[`configuration.md`](../../configuration.md). Full reference:",
        "[`configuration-reference.md`](../configuration-reference.md).",
        "",
        *_props_table(props, defs, required=required),
        "",
    ]
    return "\n".join(lines)


def _render_config_type_index(def_names: list[str]) -> str:
    """Render index of configuration schema type pages."""
    lines = [
        _HEADER.rstrip(),
        "# Configuration schema types (index)",
        "",
        "One page per ``mask-rules.yaml`` schema block. Regenerate with",
        "``make docs-generate``.",
        "",
        "| Type | Page |",
        "|------|------|",
    ]
    for name in def_names:
        slug = name.lower()
        lines.append(f"| `{name}` | [{name}]({slug}.md) |")
    lines.append("")
    return "\n".join(lines)


def _render_config_type_pages(schema: dict[str, Any]) -> dict[Path, str]:
    """Generate one indexable page per JSON Schema ``$defs`` entry."""
    defs: dict[str, Any] = schema.get("$defs", {})
    names = sorted(name for name, item in defs.items() if item.get("properties"))
    outputs: dict[Path, str] = {
        CONFIG_TYPES_DIR / "index.md": _render_config_type_index(names),
    }
    for name in names:
        slug = name.lower()
        outputs[CONFIG_TYPES_DIR / f"{slug}.md"] = _render_config_type_page(
            name, defs[name], defs
        )
    return outputs


def _outputs() -> dict[Path, str]:
    """Compute all generated file paths and contents."""
    schema_json = export_json_schema()
    schema = json.loads(schema_json)
    outputs: dict[Path, str] = {
        GENERATED / "mask-rules.schema.json": schema_json + "\n",
        GENERATED / "configuration-reference.md": _render_schema_markdown(schema),
        GENERATED / "cli-reference.md": _render_cli_markdown(),
    }
    outputs.update(_render_error_pages())
    outputs.update(_render_config_type_pages(schema))
    return outputs


def _write_outputs(outputs: dict[Path, str]) -> None:
    """Write generated documentation files to disk."""
    GENERATED.mkdir(parents=True, exist_ok=True)
    expected = set(outputs.keys())
    for subdir in (ERRORS_DIR, CONFIG_TYPES_DIR):
        subdir.mkdir(parents=True, exist_ok=True)
        for stale in subdir.glob("*.md"):
            if stale not in expected:
                stale.unlink()
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _check_outputs(outputs: dict[Path, str]) -> list[Path]:
    """Return paths whose on-disk content differs from expected."""
    stale: list[Path] = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
    return stale


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint for doc generation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files are missing or out of date.",
    )
    args = parser.parse_args(argv)
    outputs = _outputs()

    if args.check:
        stale = _check_outputs(outputs)
        if stale:
            names = ", ".join(str(p.relative_to(ROOT)) for p in stale)
            print(f"Stale generated docs: {names}", file=sys.stderr)
            print("Run: make docs-generate", file=sys.stderr)
            return 1
        return 0

    _write_outputs(outputs)
    for path in outputs:
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
